steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA',  
    '--build-arg=REACT_APP_API_URL=$_REACT_APP_API_URL', 
    '--build-arg=REACT_APP_DEMO=$_REACT_APP_DEMO', 
    '.' 
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud 
  args: ['run', 'deploy', '$_SERVICE_NAME', '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA
timeout: '1600s'
