steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-nbbl-cms:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  env: 
  - REACT_APP_API_URL=$_REACT_APP_API_URL
  args: ['push', 'gcr.io/$PROJECT_ID/react-nbbl-cms:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud 
  args: ['run', 'deploy', 'react-nbbl-cms', '--image', 'gcr.io/$PROJECT_ID/react-nbbl-cms:$SHORT_SHA', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/react-nbbl-cms:$SHORT_SHA
timeout: '1600s'
