steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  env: 
  - REACT_APP_API_URL=${_REACT_APP_API_URL}
  - REACT_APP_DEMO_TWO=${_REACT_APP_DEMO_TWO}
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-react-demo:$SHORT_SHA',  '--build-arg=REACT_APP_API_URL=$_REACT_APP_API_URL', '--build-arg=REACT_APP_DEMO=$_REACT_APP_DEMO', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  env: 
  - REACT_APP_API_URL=${_REACT_APP_API_URL}
  - REACT_APP_DEMO_TWO=${_REACT_APP_DEMO_TWO}
  args: ['push', 'gcr.io/$PROJECT_ID/gcp-react-demo:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud 
  env: 
  - REACT_APP_API_URL=${_REACT_APP_API_URL}
  - REACT_APP_DEMO_TWO=${_REACT_APP_DEMO_TWO}
  args: ['run', 'deploy', 'gcp-react-demo', '--image', 'gcr.io/$PROJECT_ID/gcp-react-demo:$SHORT_SHA', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/gcp-react-demo:$SHORT_SHA
timeout: '1600s'
